steps:
  # Install dependencies
  - name: "node:18"
    entrypoint: npm
    args: ["install"]

  # Deploy to Cloud Functions
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - vertixol-website
      - --runtime=nodejs18
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=vertixolWebsite
      - --source=.
      - --region=us-central1

timeout: "540s"
